# Generated by Django 3.0.7 on 2020-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200614_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.CharField(max_length=50),
        ),
    ]
