# Generated by Django 3.0.7 on 2020-06-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200616_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='info',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='mobile',
        ),
    ]
