# Generated by Django 3.0.7 on 2020-06-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200620_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='posting',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
