# Generated by Django 3.0.7 on 2020-06-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200620_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gradation',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
