# Generated by Django 3.0.7 on 2020-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200620_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gradation',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
