# Generated by Django 3.0.7 on 2020-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200620_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.PositiveIntegerField(default=880),
        ),
    ]
